name: Deploy React to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Pull your code
      - uses: actions/checkout@v4

      # Install Node so we can build React
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install dependencies
      - run: npm install

      # Build your React app
      - run: npm run build

      # Deploy to Firebase using new official action
      - uses: firebase/actions hosting-deploy@v1
        with:
          channelId: live
          projectId: kdss-479615
          entryPoint: .
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
